---
:project: pulp
:github_org: pulp
:releases:
  :2.15.3:
    :redmine_release_id: 59
:repos:
  :pulp:
    :main: true
    :branch: 2.15-release
    :repo: https://github.com/pulp/pulp
    :version_branch: true
  :pulp_rpm:
    :main: true
    :branch: 2.15-release
    :repo: https://github.com/pulp/pulp_rpm
    :version_branch: true
  :pulp_puppet:
    :main: true
    :branch: 2.15-release
    :repo: https://github.com/pulp/pulp_puppet
    :version_branch: true
  :pulp_docker:
    :main: true
    :branch: 3.1-release
    :repo: https://github.com/pulp/pulp_docker
    :version_branch: true
  :pulp_deb:
    :main: true
    :branch: 1.6-release
    :repo: https://github.com/pulp/pulp_deb
    :version_branch: true
  :pulp_python:
    :main: true
    :branch: 2.0-release
    :repo: https://github.com/pulp/pulp_python
    :version_branch: true
  :pulp_ostree:
    :main: true
    :branch: 1.3-release
    :repo: https://github.com/pulp/pulp_ostree
    :version_branch: true
