---
:project: katello
:github_org: katello
:releases:
  :2.2:
    :redmine_release_id: 504
  :2.2.1:
    :redmine_release_id: 503
  :2.2.2:
    :redmine_release_id: 502
  :2.2.3:
    :redmine_release_id: 544
  :2.2.4:
    :redmine_release_id: 501
:code_name: Maibock
:repos:
  :katello:
    :main: true
    :branch: KATELLO-2.2
    :repo: https://github.com/Katello/katello.git
  :katello-installer:
    :branch: KATELLO-2.2
    :repo: https://github.com/Katello/katello-installer.git
  :hammer-cli-katello:
    :branch: 0.0.10
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello.org:
    :branch: KATELLO-2.2
    :repo: https://github.com/Katello/katello.org.git
  :katello-misc:
    :branch: KATELLO-2.2
    :repo: https://github.com/Katello/katello-misc.git
:ignores:
  - 9070
  - 9474
  - 9484
  - 9345
  - 9582
  - 9995
  - 9749
  - 7940
  - 8544
  - 9839
  - 10224
  - 10616
