---
:project: katello
:github_org: katello
:prior_releases:
  :2.4.1:
    :redmine_release_id: 497
  :2.4.2:
    :redmine_release_id: 496
:releases:
  :3.0:
    :redmine_release_id: 494
  :3.0.1:
    :redmine_release_id: 493
:code_name: Saison
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.0
    :repo: https://github.com/Katello/katello.git
  :katello-selinux:
    :branch: KATELLO-3.0
    :repo: https://github.com/Katello/katello-selinux.git
  :katello-installer:
    :branch: KATELLO-3.0
    :repo: https://github.com/Katello/katello-installer.git
  :hammer-cli-katello:
    :branch: 0.0.25
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello.org:
    :branch: KATELLO-3.0
    :repo: https://github.com/Katello/katello.org.git
  :katello-packaging:
    :branch: KATELLO-3.0
    :repo: https://github.com/Katello/katello-packaging.git
  :puppet-katello:
    :branch: 4.0.0
    :repo: https://github.com/Katello/puppet-katello.git
  :puppet-capsule:
    :branch: 2.1.0
    :repo: https://github.com/Katello/puppet-capsule.git
  :puppet-pulp:
    :branch: 3.2.0
    :repo: https://github.com/Katello/puppet-pulp.git
  :katello-agent:
    :branch: 2.5.0
    :repo: https://github.com/Katello/katello-agent.git
:ignores:
  - 12841
  - 10533
  - 12000
  - 9848
