---
:project: katello
:github_org: katello
:prior_releases:
#  :3.0.0:
#    :redmine_release_id: 86
#  :3.0.1:
#    :redmine_release_id: 144
#  :3.0.2:
#    :redmine_release_id: 168
  :3.0.3:
    :redmine_release_id: 542
:releases:
  :3.1:
    :redmine_release_id: 491
:code_name: California Common
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.1
    :repo: https://github.com/Katello/katello.git
  :katello-selinux:
    :branch: KATELLO-3.1
    :repo: https://github.com/Katello/katello-selinux.git
  :katello-installer:
    :branch: KATELLO-3.1
    :repo: https://github.com/Katello/katello-installer.git
  :hammer-cli-katello:
    :branch: 0.0.26
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello.org:
    :branch: KATELLO-3.1
    :repo: https://github.com/Katello/katello.org.git
  :katello-packaging:
    :branch: KATELLO-3.1
    :repo: https://github.com/Katello/katello-packaging.git
  :puppet-katello:
    :branch: 5.0.1
    :repo: https://github.com/Katello/puppet-katello.git
  :puppet-capsule:
    :branch: 3.0.0
    :repo: https://github.com/Katello/puppet-capsule.git
  :puppet-pulp:
    :branch: 3.3.1
    :repo: https://github.com/Katello/puppet-pulp.git
  :katello-agent:
    :branch: 2.6.0
    :repo: https://github.com/Katello/katello-agent.git
:ignores:
