---
:project: katello
:github_org: katello
:prior_releases:
  :3.7.0:
    :redmine_version_id: 264
  :3.7.1:
    :redmine_version_id: 355
  :3.7.2:
    :redmine_version_id: 931
:releases:
  :3.8.0:
    :redmine_version_id: 356
  :3.8.1:
    :redmine_version_id: 917
:code_name: Stout
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.8
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-installer:
    :branch: KATELLO-3.8
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.19
    :repo: https://github.com/theforeman/foreman-packaging.git
  :puppet-katello:
    :branch: 8.0.2
    :repo: https://github.com/Katello/puppet-katello
  :hammer-cli-katello:
    :branch: 0.14.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :foreman-packaging:
    :branch: rpm/1.19
    :repo: https://github.com/theforeman/foreman-packaging.git
  :katello-host-tools:
    :branch: 3.3.5
    :repo: https://github.com/Katello/katello-host-tools.git
  :bastion:
    :branch: 6.1.12
    :repo: https://github.com/Katello/bastion.git
  :puppet-pulp:
    :branch: 5.5.0
    :repo: https://github.com/Katello/puppet-pulp
  :puppet-candlepin:
    :branch: 5.1.1
    :repo: https://github.com/Katello/puppet-candlepin
  :puppet-certs:
    :branch: 4.2.0
    :repo: https://github.com/Katello/puppet-certs
  :puppet-qpid:
    :branch: 4.2.2
    :repo: https://github.com/Katello/puppet-qpid
  :puppet-foreman_proxy_content:
    :branch: 7.2.0
    :repo: https://github.com/Katello/puppet-foreman_proxy_content
  :puppet-service_wait:
    :branch: 1.0.4
    :repo: https://github.com/theforeman/puppet-service_wait.git
:ignores:
  - 23322
  - 22961
  - 24127
  - 24317
  - 24341
  - 23785
  - 24309
  - 22565
  - 22808
  - 22897
  - 23036
  - 23201
  - 23109
  - 23265
  - 23176
  - 22377
  - 23284
  - 22648
  - 23541
  - 22795
  - 23925
  - 23767
  - 22376
  - 23978
  - 24070
  - 23198
  - 22754
  - 23648
  - 23283
  - 23171
  - 23946
  - 23542
  - 23032
  - 23762
  - 23786
  - 23760
  - 23160
  - 24095
  - 24223
  - 24079
  - 22947
  - 23988
  - 23287
  - 23302
  - 23696
  - 23745
  - 22967
  - 22595
  - 22972
  - 23330
  - 24070
  - 22802
  - 23676
  - 23706
  - 24523
  - 24678
  - 24651
  - 24529
  - 23886
  - 23992
  - 24243
  - 18282
  - 24168
  - 24543
  - 24305
  - 24292
  - 24499
  - 23989
  - 24005
  - 24275
  - 24390
  - 24423
  - 24273
  - 24389
  - 24265
  - 23750
  - 22568
  - 24143
  - 24310
  - 22914
  - 24374
  - 24336
  - 24335
  - 23510
  - 24288
  - 24354
  - 24337
  - 22900
  - 24324
  - 24188
  - 24215
  - 24304
  - 24229
  - 24129
  - 23903
  - 24141
  - 24242
  - 23063
  - 24055

:gpg_key: '10668686'
:mash_scripts:
 - katello-3.8-thirdparty-candlepin-rhel7
 - katello-3.8-rhel7
 - katello-3.8-client-rhel7
 - katello-3.8-client-rhel6
 - katello-3.8-client-rhel5
 - katello-3.8-client-fedora27
 - katello-3.8-client-fedora28
 - katello-3.8-client-sles11
 - katello-3.8-client-sles12
:tags:
  - name: katello-3.8-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.8-thirdparty-pulp-rhel7
    based_off: katello-thirdparty-pulp-rhel7
    arches:
      - x86_64
  - name: katello-3.8-thirdparty-pulp-rhel6
    based_off: katello-thirdparty-pulp-rhel6
    arches:
      - x86_64
  - name: katello-3.8-thirdparty-pulp-rhel5
    based_off: katello-thirdparty-pulp-rhel5
    arches:
      - x86_64
  - name: katello-3.8-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.8-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.8-rhel7-override: null
      katello-3.8-client-rhel7: null
    build_target: katello-3.8-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.8-rhel7-build:
        katello-3.8-rhel7-override: 0
        foreman-plugins-1.19-rhel7-override: 3
        foreman-1.19-nonscl-rhel7: 4
        foreman-1.19-rhel7: 10
      katello-3.8-rhel7-override:
        katello-3.8-rhel7: 0
      katello-3.8-rhel7:
        katello-3.8-thirdparty-rhel7: 0
      katello-3.8-client-rhel7:
        katello-3.8-rhel7: 0
        katello-3.8-thirdparty-pulp-rhel7: 2
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-sclo-sclo-rhel-7
      - centos-7-server
      - rhel-7.0-server
      - foreman-rails-1.19-rhel-7
  - name: katello-3.8-rhel6
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.8-thirdparty-rhel6: katello-thirdparty-rhel6
      katello-3.8-rhel6-override: null
      katello-3.8-client-rhel6: null
    build_target: katello-3.8-rhel6-build
    build_package_group_source_tag: katello-nightly-rhel6-build
    arches:
      - x86_64
    inherits:
      katello-3.8-rhel6-build:
        katello-3.8-rhel6-override: 0
      katello-3.8-rhel6-override:
        katello-3.8-rhel6: 1
      katello-3.8-rhel6:
        katello-3.8-thirdparty-rhel6: 0
      katello-3.8-client-rhel6:
        katello-3.8-rhel6: 0
        katello-3.8-thirdparty-pulp-rhel6: 2
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
  - name: katello-3.8-rhel5
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.8-rhel5-override: null
      katello-3.8-client-rhel5: null
    build_target: katello-3.8-rhel5-build
    build_package_group_source_tag: katello-nightly-rhel5-build
    arches:
      - x86_64
    inherits:
      katello-3.8-rhel5-build:
        katello-3.8-rhel5-override: 0
      katello-3.8-rhel5-override:
        katello-3.8-rhel5: 0
      katello-3.8-rhel5: {}
      katello-3.8-client-rhel5:
        katello-3.8-rhel5: 0
        katello-3.8-thirdparty-pulp-rhel5: 2
    external_repos:
      - rhel-5.9-server
      - epel-5
  - name: katello-3.8-fedora27
    based_off: katello-nightly-fedora27
    helper_tags:
      katello-3.8-client-fedora27: null
    build_target: katello-3.8-fedora27-build
    build_package_group_source_tag: katello-nightly-fedora27-build
    arches:
      - x86_64
    inherits:
      katello-3.8-fedora27-build:
        katello-3.8-fedora27: 0
      katello-3.8-fedora27: {}
      katello-3.8-client-fedora27:
        katello-3.8-fedora27: 0
    external_repos:
      - fedora-27-updates
      - fedora-27
  - name: katello-3.8-fedora28
    based_off: katello-nightly-fedora28
    helper_tags:
      katello-3.8-client-fedora28: null
    build_target: katello-3.8-fedora28-build
    build_package_group_source_tag: katello-nightly-fedora28-build
    arches:
      - x86_64
    inherits:
      katello-3.8-fedora28-build:
        katello-3.8-fedora28: 0
      katello-3.8-fedora28: {}
      katello-3.8-client-fedora28:
        katello-3.8-fedora28: 0
    external_repos:
      - fedora-28-updates
      - fedora-28
  - name: katello-3.8-sles12
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.8-client-sles12: null
    inherits:
      katello-3.8-client-sles12:
        katello-3.8-sles12: 0
  - name: katello-3.8-sles11
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.8-client-sles11: null
    inherits:
      katello-3.8-client-sles11:
        katello-3.8-sles11: 0

