---
:project: foreman
:releases:
  :1.10.0:
    :redmine_release_id: 63
  :1.10.1:
    :redmine_release_id: 104
  :1.10.2:
    :redmine_release_id: 123
  :1.10.3:
    :redmine_release_id: 145
  :1.10.4:
    :redmine_release_id: 152
:repos:
  :foreman:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman.git
  :smart-proxy:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/smart-proxy.git
  :foreman-selinux:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman-selinux.git
  :foreman-installer:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman-installer.git
:ignores:
  # Hammer commit is being picked up, the Foreman commit is in
  - 10731
  # Installer module changes, all in
  - 11681
  - 11655
  - 11781
  - 12157
  # Packaging deb/1.10 changes, all in
  - 11152
