---
:project: katello
:github_org: katello
:nightly: true
:tags:
  - name: katello-thirdparty-candlepin-rhel7
    based_off: null
    arches:
      - x86_64
  - name: katello-thirdparty-pulp-rhel7
    based_off: null
    arches:
      - x86_64
  - name: katello-thirdparty-pulp-rhel6
    based_off: null
    arches:
      - x86_64
  - name: katello-thirdparty-pulp-rhel5
    based_off: null
    arches:
      - x86_64
  - name: katello-nightly-rhel7
    based_off: null
    helper_tags:
      katello-thirdparty-rhel7: null
      katello-nightly-rhel7-override: null
      katello-nightly-client-rhel7: null
    build_target: katello-nightly-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-nightly-rhel7-build:
        katello-nightly-rhel7-override: 0
        foreman-plugins-nightly-rhel7-override: 3
        foreman-nightly-nonscl-rhel7: 4
        foreman-nightly-rhel7: 10
      katello-nightly-rhel7-override:
        katello-nightly-rhel7: 0
      katello-nightly-rhel7:
        katello-thirdparty-rhel7: 0
      katello-nightly-client-rhel7:
        katello-nightly-rhel7: 0
        katello-thirdparty-pulp-rhel7: 2
    external_repos:
      - rhel-7.0-server
      - rhel-7.0-server-optional
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-sclo-sclo-rhel-7
      - centos-7-server
      - tfm-ror51-rhel-7
  - name: katello-nightly-rhel6
    based_off: null
    helper_tags:
      katello-thirdparty-rhel6: null
      katello-nightly-rhel6-override: null
      katello-nightly-client-rhel6: null
    build_target: katello-nightly-rhel6-build
    build_package_group_source_tag: katello-nightly-rhel6-build
    arches:
      - x86_64
    inherits:
      katello-nightly-rhel6-build:
        katello-nightly-rhel6-override: 0
      katello-nightly-rhel6-override:
        katello-nightly-rhel6: 1
      katello-nightly-rhel6:
        katello-thirdparty-rhel6: 0
      katello-nightly-client-rhel6:
        katello-nightly-rhel6: 0
        katello-thirdparty-pulp-rhel6: 2
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
  - name: katello-nightly-rhel5
    based_off: null
    helper_tags:
      katello-nightly-rhel5-override: null
      katello-nightly-client-rhel5: null
    build_target: katello-nightly-rhel5-build
    build_package_group_source_tag: katello-nightly-rhel5-build
    arches:
      - x86_64
    inherits:
      katello-nightly-rhel5-build:
        katello-nightly-rhel5-override: 0
      katello-nightly-rhel5-override:
        katello-nightly-rhel5: 0
      katello-nightly-rhel5: {}
      katello-nightly-client-rhel5:
        katello-nightly-rhel5: 0
        katello-thirdparty-pulp-rhel5: 2
    external_repos:
      - rhel-5.9-server
      - epel-5
  - name: katello-nightly-fedora27
    based_off: null
    helper_tags:
      katello-nightly-client-fedora27: null
    build_target: katello-nightly-fedora27-build
    build_package_group_source_tag: katello-nightly-fedora26-build
    arches:
      - x86_64
    inherits:
      katello-nightly-fedora27-build:
        katello-nightly-fedora27: 0
      katello-nightly-fedora27: {}
      katello-nightly-client-fedora27:
        katello-nightly-fedora27: 0
    external_repos:
      - fedora-27-updates
      - fedora-27
  - name: katello-nightly-fedora28
    based_off: null
    helper_tags:
      katello-nightly-client-fedora28: null
    build_target: katello-nightly-fedora28-build
    build_package_group_source_tag: katello-nightly-fedora27-build
    arches:
      - x86_64
    inherits:
      katello-nightly-fedora28-build:
        katello-nightly-fedora28: 0
      katello-nightly-fedora28: {}
      katello-nightly-client-fedora28:
        katello-nightly-fedora28: 0
    external_repos:
      - fedora-28-updates
      - fedora-28
  - name: katello-nightly-sles12
    based_off: null
    arches:
      - x86_64
    helper_tags:
      katello-nightly-client-sles12: null
    inherits:
      katello-nightly-client-sles12:
        katello-nightly-sles12: 0
  - name: katello-nightly-sles11
    based_off: null
    arches:
      - x86_64
    helper_tags:
      katello-nightly-client-sles11: null
    inherits:
      katello-nightly-client-sles11:
        katello-nightly-sles11: 0
