---
:project: foreman
:github_org: theforeman
:releases:
  :2.1.0:
    :redmine_version_id: 1199
:mash_scripts:
  - foreman-2.1-rhel7-dist
  - foreman-2.1-el8
  - foreman-plugins-2.1-rhel7-dist
  - foreman-plugins-2.1-el8
  - foreman-client-2.1-el8
  - foreman-client-2.1-rhel7
  - foreman-client-2.1-rhel6
  - foreman-client-2.1-rhel5
  - foreman-client-2.1-sles11
  - foreman-client-2.1-sles12
:strict_keys: true
:gpg_key: B6F08CCF
:repos: []
:tags:
  - name: foreman-2.1-nonscl-rhel7
    based_off: foreman-nightly-nonscl-rhel7
    helper_tags:
      foreman-2.1-nonscl-rhel7-override: null
    build_target: foreman-2.1-nonscl-rhel7-build
    build_package_group_source_tag: foreman-2.1-nonscl-rhel7-build
    arches:
      - x86_64
    inherits:
      foreman-2.1-nonscl-rhel7-build:
        foreman-2.1-nonscl-rhel7-override: 0
      foreman-2.1-nonscl-rhel7-override:
        foreman-2.1-nonscl-rhel7: 0
    external_repos:
      - epel-7
      - puppetlabs-puppet6-rhel-7
      - centos-7-server-updates
      - centos-7-server
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-2.1-rhel7
    based_off: foreman-nightly-rhel7
    helper_tags:
      foreman-2.1-rhel7-override: null
    build_target: foreman-2.1-rhel7-build
    build_package_group_source_tag: foreman-2.1-rhel7-build
    arches:
      - x86_64
    inherits:
      foreman-2.1-rhel7-build:
        foreman-2.1-rhel7-override: 0
        foreman-2.1-nonscl-rhel7: 10
      foreman-2.1-rhel7-override:
        foreman-2.1-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
      - puppetlabs-puppet6-rhel-7
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - foreman-build
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-rpm-config
        - rh-ruby25-scldevel
        - rpm-build
        - scl-utils-build
        - sed
        - shadow-utils
        - tar
        - tfm-build
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - foreman-build
        - redhat-rpm-config
        - rh-ruby25-scldevel
        - rhpkg-simple
        - rpm-build
        - scl-utils-build
        - shadow-utils
        - tfm-build
  - name: foreman-2.1-el8
    based_off: foreman-nightly-el8
    helper_tags:
      foreman-2.1-el8-override: null
    build_target: foreman-2.1-el8-build
    build_package_group_source_tag: foreman-2.1-el8-build
    arches:
      - x86_64
    inherits:
      foreman-2.1-el8-build:
        foreman-2.1-el8-override: 0
      foreman-2.1-el8-override:
        foreman-2.1-el8: 0
    external_repos:
      - test-flat-el8
      - centos8-devel
      - puppetlabs-puppet6-rhel-8
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - foreman-build
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - foreman-build
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-plugins-2.1-nonscl-rhel7
    based_off: foreman-plugins-nightly-nonscl-rhel7
    helper_tags:
      foreman-plugins-2.1-nonscl-rhel7-override: null
    build_target: foreman-plugins-2.1-nonscl-rhel7-build
    build_package_group_source_tag: foreman-plugins-2.1-nonscl-rhel7-build
    arches:
      - x86_64
    inherits:
      foreman-plugins-2.1-nonscl-rhel7-build:
        foreman-plugins-2.1-nonscl-rhel7-override: 0
        foreman-2.1-rhel7: 15
        foreman-2.1-nonscl-rhel7: 10
      foreman-plugins-2.1-nonscl-rhel7-override:
        foreman-plugins-2.1-nonscl-rhel7: 0
    external_repos:
      - epel-7
      - centos-7-server-updates
      - centos-7-server
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-plugins-2.1-rhel7
    based_off: foreman-plugins-nightly-rhel7
    helper_tags:
      foreman-plugins-2.1-rhel7-override: null
    build_target: foreman-plugins-2.1-rhel7-build
    build_package_group_source_tag: foreman-plugins-2.1-rhel7-build
    arches:
      - x86_64
    inherits:
      foreman-plugins-2.1-rhel7-build:
        foreman-plugins-2.1-rhel7-override: 0
        foreman-plugins-2.1-nonscl-rhel7: 5
        foreman-2.1-rhel7: 15
        foreman-2.1-nonscl-rhel7: 20
      foreman-plugins-2.1-rhel7-override:
        foreman-plugins-2.1-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - foreman-build
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-rpm-config
        - rh-ruby25-scldevel
        - rpm-build
        - scl-utils-build
        - sed
        - shadow-utils
        - tar
        - tfm-build
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - foreman-build
        - redhat-rpm-config
        - rh-ruby25-scldevel
        - rhpkg-simple
        - rpm-build
        - scl-utils-build
        - shadow-utils
        - tfm-build
  - name: foreman-plugins-2.1-el8
    based_off: foreman-plugins-nightly-el8
    helper_tags:
      foreman-plugins-2.1-el8-override: null
    build_target: foreman-plugins-2.1-el8-build
    build_package_group_source_tag: foreman-plugins-2.1-el8-build
    arches:
      - x86_64
    inherits:
      foreman-plugins-2.1-el8-build:
        foreman-plugins-2.1-el8-override: 0
        foreman-2.1-el8: 15
      foreman-plugins-2.1-el8-override:
        foreman-plugins-2.1-el8: 0
    external_repos:
      - centos8-baseos
      - centos8-appstream
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - foreman-build
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - foreman-build
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-2.1-rhel7-dist
    based_off: foreman-nightly-rhel7-dist
    inherits:
      foreman-2.1-rhel7-dist:
        foreman-2.1-rhel7: 20
        foreman-2.1-nonscl-rhel7: 10
  - name: foreman-plugins-2.1-rhel7-dist
    based_off: foreman-plugins-nightly-rhel7-dist
    inherits:
      foreman-plugins-2.1-rhel7-dist:
        foreman-plugins-2.1-rhel7: 2
        foreman-plugins-2.1-nonscl-rhel7: 0
  - name: foreman-client-2.1-rhel5
    based_off: foreman-client-nightly-rhel5
    helper_tags:
      foreman-client-2.1-rhel5-override: null
      foreman-client-2.1-rhel5: null
    build_target: foreman-client-2.1-rhel5-build
    arches:
      - x86_64
    inherits:
      foreman-client-2.1-rhel5-build:
        foreman-client-2.1-rhel5-override: 0
      foreman-client-2.1-rhel5-override:
        foreman-client-2.1-rhel5: 0
      foreman-client-2.1-rhel5: {}
    external_repos:
      - rhel-5.9-server
      - epel-5
    build_groups:
      build:
        - bash
        - buildsys-macros
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-release-server
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - buildsys-macros
        - redhat-release-server
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-client-2.1-rhel6
    based_off: foreman-client-nightly-rhel6
    helper_tags:
      foreman-client-2.1-rhel6-override: null
      foreman-client-2.1-rhel6: null
    build_target: foreman-client-2.1-rhel6-build
    arches:
      - x86_64
    inherits:
      foreman-client-2.1-rhel6-build:
        foreman-client-2.1-rhel6-override: 0
      foreman-client-2.1-rhel6-override:
        foreman-client-2.1-rhel6: 0
      foreman-client-2.1-rhel6: {}
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
    build_groups:
      build:
        - bash
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-release-server
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - redhat-release-server
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-client-2.1-el8
    based_off: foreman-client-nightly-el8
    helper_tags:
      foreman-client-2.1-el8-override: null
      foreman-client-2.1-el8: null
    build_target: foreman-client-2.1-el8-build
    arches:
      - x86_64
    inherits:
      foreman-client-2.1-el8-build:
        foreman-client-2.1-el8-override: 0
      foreman-client-2.1-el8-override:
        foreman-client-2.1-el8: 0
      foreman-client-2.1-el8: {}
    external_repos:
      - centos8-baseos
      - centos8-appstream
    build_groups:
      build:
        - bash
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - platform-python
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - platform-python
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-client-2.1-rhel7
    based_off: foreman-client-nightly-rhel7
    helper_tags:
      foreman-client-2.1-rhel7-override: null
      foreman-client-2.1-rhel7: null
    build_target: foreman-client-2.1-rhel7-build
    arches:
      - x86_64
    inherits:
      foreman-client-2.1-rhel7-build:
        foreman-client-2.1-rhel7-override: 0
      foreman-client-2.1-rhel7-override:
        foreman-client-2.1-rhel7: 0
      foreman-client-2.1-rhel7: {}
    external_repos:
      - epel-7
      - centos-7-server-updates
      - centos-7-server
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: foreman-client-2.1-sles12
    based_off: foreman-client-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      foreman-client-2.1-sles12: null
    inherits:
      foreman-client-2.1-sles12: {}
  - name: foreman-client-2.1-sles11
    based_off: foreman-client-nightly-sles11
    arches:
      - x86_64
    helper_tags:
      foreman-client-2.1-sles11: null
    inherits:
      foreman-client-2.1-sles11: {}
